//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment5Application.ivanService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ivanService.IAssignment6Service")]
    public interface IAssignment6Service {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssignment6Service/Weather5Day", ReplyAction="http://tempuri.org/IAssignment6Service/Weather5DayResponse")]
        string[] Weather5Day(int zipCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssignment6Service/Weather5Day", ReplyAction="http://tempuri.org/IAssignment6Service/Weather5DayResponse")]
        System.Threading.Tasks.Task<string[]> Weather5DayAsync(int zipCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssignment6Service/NewsFocus", ReplyAction="http://tempuri.org/IAssignment6Service/NewsFocusResponse")]
        string[] NewsFocus(string[] topics);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssignment6Service/NewsFocus", ReplyAction="http://tempuri.org/IAssignment6Service/NewsFocusResponse")]
        System.Threading.Tasks.Task<string[]> NewsFocusAsync(string[] topics);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssignment6Service/tempConverter", ReplyAction="http://tempuri.org/IAssignment6Service/tempConverterResponse")]
        int tempConverter(int temp, string conversionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssignment6Service/tempConverter", ReplyAction="http://tempuri.org/IAssignment6Service/tempConverterResponse")]
        System.Threading.Tasks.Task<int> tempConverterAsync(int temp, string conversionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssignment6Service/sortingService", ReplyAction="http://tempuri.org/IAssignment6Service/sortingServiceResponse")]
        int[] sortingService(int[] nums, string algorithm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssignment6Service/sortingService", ReplyAction="http://tempuri.org/IAssignment6Service/sortingServiceResponse")]
        System.Threading.Tasks.Task<int[]> sortingServiceAsync(int[] nums, string algorithm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssignment6Service/currentConversionService", ReplyAction="http://tempuri.org/IAssignment6Service/currentConversionServiceResponse")]
        int currentConversionService(int money, string conversionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssignment6Service/currentConversionService", ReplyAction="http://tempuri.org/IAssignment6Service/currentConversionServiceResponse")]
        System.Threading.Tasks.Task<int> currentConversionServiceAsync(int money, string conversionString);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAssignment6ServiceChannel : Assignment5Application.ivanService.IAssignment6Service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Assignment6ServiceClient : System.ServiceModel.ClientBase<Assignment5Application.ivanService.IAssignment6Service>, Assignment5Application.ivanService.IAssignment6Service {
        
        public Assignment6ServiceClient() {
        }
        
        public Assignment6ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Assignment6ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Assignment6ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Assignment6ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] Weather5Day(int zipCode) {
            return base.Channel.Weather5Day(zipCode);
        }
        
        public System.Threading.Tasks.Task<string[]> Weather5DayAsync(int zipCode) {
            return base.Channel.Weather5DayAsync(zipCode);
        }
        
        public string[] NewsFocus(string[] topics) {
            return base.Channel.NewsFocus(topics);
        }
        
        public System.Threading.Tasks.Task<string[]> NewsFocusAsync(string[] topics) {
            return base.Channel.NewsFocusAsync(topics);
        }
        
        public int tempConverter(int temp, string conversionString) {
            return base.Channel.tempConverter(temp, conversionString);
        }
        
        public System.Threading.Tasks.Task<int> tempConverterAsync(int temp, string conversionString) {
            return base.Channel.tempConverterAsync(temp, conversionString);
        }
        
        public int[] sortingService(int[] nums, string algorithm) {
            return base.Channel.sortingService(nums, algorithm);
        }
        
        public System.Threading.Tasks.Task<int[]> sortingServiceAsync(int[] nums, string algorithm) {
            return base.Channel.sortingServiceAsync(nums, algorithm);
        }
        
        public int currentConversionService(int money, string conversionString) {
            return base.Channel.currentConversionService(money, conversionString);
        }
        
        public System.Threading.Tasks.Task<int> currentConversionServiceAsync(int money, string conversionString) {
            return base.Channel.currentConversionServiceAsync(money, conversionString);
        }
    }
}
