//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Assignment5Application.DynamicData.FieldTemplates
{
    public partial class Web
    {
        protected global::System.Web.UI.WebControls.Literal Literal1;
    }
}
